# Generated by Django 5.0.4 on 2024-11-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_books_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
