# Generated by Django 5.0.4 on 2024-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_subject_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cart',
            field=models.BooleanField(default=False),
        ),
    ]
